spring:
  application:
    name: trainee-api-gateway
  profiles:
    default: local

  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        probes:
          enabled: true