apiVersion: v1
kind: Secret
metadata:
  name: trainee-secrets
  namespace: trainee
type: Opaque
stringData:
  AUTH_DB_USER: "postgres"
  AUTH_DB_PASSWORD: "postgres"

  USER_DB_USER: "postgres"
  USER_DB_PASSWORD: "postgres"

  REDIS_PASSWORD: "redis123"

  ORDER_DB_USER: "postgres"
  ORDER_DB_PASSWORD: "postgres"

  PAYMENT_MONGO_ROOT_USERNAME: "mongo"
  PAYMENT_MONGO_ROOT_PASSWORD: "password"
  PAYMENT_MONGO_URI: "mongodb://mongo:password@payment-mongodb:27017/payment_db?authSource=admin"

  JWT_SECRET: "very-strong-secret"