apiVersion: v1
kind: Secret
metadata:
  name: trainee-secrets
  namespace: trainee
type: Opaque
stringData:
  AUTH_DB_USER: "postgres"
  AUTH_DB_PASSWORD: "postgres"

  USER_DB_USER: "postgres"
  USER_DB_PASSWORD: "postgres"

  REDIS_PASSWORD: "redis123"

  JWT_SECRET: "very-strong-secret"