apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres
  namespace: trainee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      containers:
        - name: auth-postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "auth_service_db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: trainee-secrets
                  key: AUTH_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trainee-secrets
                  key: AUTH_DB_PASSWORD