apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-postgres
  namespace: trainee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-postgres
  template:
    metadata:
      labels:
        app: order-postgres
    spec:
      containers:
        - name: order-postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: trainee-config
                  key: ORDER_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: trainee-secrets
                  key: ORDER_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trainee-secrets
                  key: ORDER_DB_PASSWORD
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - order_service_db
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - order_service_db
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5