apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-postgres
  namespace: trainee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-postgres
  template:
    metadata:
      labels:
        app: user-postgres
    spec:
      containers:
        - name: user-postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: trainee-config
                  key: USER_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: trainee-secrets
                  key: USER_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trainee-secrets
                  key: USER_DB_PASSWORD