apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: trainee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: dzarembo/trainee-auth-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILE_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: trainee-config
                  key: SPRING_PROFILES_ACTIVE
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: trainee-config
                  key: AUTH_DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: trainee-secrets
                  key: AUTH_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trainee-secrets
                  key: AUTH_DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: trainee-secrets
                  key: JWT_SECRET