apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: trainee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: dzarembo/trainee-user-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: trainee-config
                  key: SPRING_PROFILES_ACTIVE

            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: trainee-config
                  key: USER_DB_URL

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: trainee-secrets
                  key: USER_DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trainee-secrets
                  key: USER_DB_PASSWORD

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: trainee-config
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: trainee-config
                  key: REDIS_PORT

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trainee-secrets
                  key: REDIS_PASSWORD